server:
  port: 8081
spring:
  application:
    name: zuul-server
    
zuul:
  routes:
    bying-car:
      path: /bying-car/**
      service-id: bying-car
    config-client:
      path: /config-client/**
      service-id: config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:9082/eureka/