server:
  port: 9082
  
spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false  #是否自己向自己注册
    fetch-registry: false  #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    service-url:
      defaultZone: http://eureka1:9082/eureka/
#  server:
#    enable-self-preservation: false
      